### ISSUE TITLE
button

### ISSUE THREAD

**Issue by jackpaster** [Tueno/MaterialLoadingIndicator#1]
Im having trouble implementing this, can you help me

**Comment by Tueno** [comment]
What trouble are you having?

**Comment by jackpaster** [comment]
@Tueno Im trying to add your loading animation to that of abprogressbutton. could you please help me.

**Comment by jackpaster** [comment]
@Tueno where you have the begginning as a button and once you press on the button it shows your material loading indicator.

**Comment by jackpaster** [comment]
@Tueno do you think you can help me please

**Comment by Tueno** [comment]
@jackpaster 
I don't know how abprogressbutton works and, whether it is able to customize the progress indicator.
Since MaterialLoadingIndicator is UIView, you can add it to UIView or CALayer, and you can start animation by calling `startAnimating()` method.
If abprogressbutton is not supporting to implement external progress indicator, you can create issue on abprogressbutton's repo to request this feature.

**Comment by jackpaster** [comment]
@Tueno putting your code and replacing the code is simple, Im just getting one small error. could i skype with you for 5 min and show you the error please.

**Comment by jackpaster** [comment]
@Tueno look I know ive been a burden with this issue. But im getting an animation error with your code. could i please skype you for a very short time

**Comment by jackpaster** [comment]
@ or instead could you change your project so that there is a button and when you click on it it gradually morphs into your material loading indicator

**Comment by jackpaster** [comment]
@Tueno Could you make your project like this https://github.com/Cleveroad/CRNetworkButton. Its a button and then it morphs into the cool loading animation you made.

**Comment by Tueno** [comment]
@jackpaster  Sorry for the delay in my response. I'll try to add morphing feature when I have time.
